#! /usr/bin/env bash
set -e

warn() { echo -e "\033[1;33mWarning: $1\033[0m"; }
info() { echo -e "\033[1;33m$1\033[0m"; }
err() { echo -e "\033[1;31mError: $1\033[0m"; }

# Check for root
[[ -z $PREFIX ]] && err "No prefix set"
name=$(basename $0)

if [[ $name == "install" ]]; then
  info "[ Installing rogue14 to $PREFIX ]"
  # Create folders
  for folder in "$PREFIX/bin" "$PREFIX/share/rogue14"; do
    [[ -d $folder ]] && echo "$folder exists" || mkdir -vp "$folder"
  done

  # Copy files
  srcdir=$(dirname $0)
  cp -v "$srcdir/rogue14" "$PREFIX/bin"
  for filetype in 6 cat doc html me; do
    cp -v "$srcdir/rogue14.$filetype" "$PREFIX/share/rogue14"
  done
  info "[ Done ]"

elif [[ $name == "remove" ]]; then
  info "[ Removing rogue14 from $PREFIX ]"
  rm -fv "$PREFIX/bin/rogue14"
  rm -frv "$PREFIX/share/rogue14"
  info "[ Done ]"
fi
