#! /usr/bin/env bash
set -e

warn() { echo -e "\033[1;33mWarning: $1\033[0m"; }
info() { echo -e "\033[1;33m$1\033[0m"; }
err() { echo -e "\033[1;31mError: $1\033[0m"; exit 1; }

# Check for root
[[ -z $PREFIX ]] && err "No prefix set"
name=$(basename $0)

bin_name="$PREFIX/bin/rogue14"
score_path="$PREFIX/share/rogue14"
score_name="$score_path/highscore"

if [[ $name == "install" ]]; then
  info "[ Installing rogue14 to $PREFIX ]"
  # Create folders
  for folder in "$PREFIX/bin" "$score_path"; do
    [[ -d $folder ]] && echo "Already exists: $folder" || mkdir -vp "$folder"
  done

  # Copy files
  srcdir=$(dirname $0)
  cp -v "$srcdir/rogue14" "$bin_name"
  touch "$score_name"

  # Set permissions
  echo -n "Attempting to set group to games and add sgid ..."
  if chgrp games "$bin_name" "$score_name" &&
     chmod 2755 "$bin_name" &&
     chmod 0664 "$score_name"; then
    echo "Success!"
    echo "All players need to be added to games group for access to highscore"
  else
    echo "Failed!"
    echo -n "You may want to create a $score_name with full"
    echo " access granted in order for everyone to be able to play"
  fi
  info "[ Installation complete ]"

elif [[ $name == "remove" ]]; then
  info "[ Uninstalling rogue14 from $PREFIX ]"
  rm -fv "$bin_name"
  rm -frv "$score_path"
  [[ -d "$PREFIX/bin" ]] && rmdir "$PREFIX/bin"
  [[ -d "$PREFIX/share" ]] && rmdir "$PREFIX/share"
  info "[ Uninstallation complete ]"
fi
